### ISSUE TITLE
Friend Core has failed to find your file. 

### ISSUE THREAD

**Issue by seem8** [FriendSoftwareLabs/friendup#1]
Since it's my first post: hello there and thanks for the repo.

After launching ./FriendCore and visiting my site I get an error:
404 - File not found!
Friend Core has failed to find your file.
Go back. 

I installed Friendup on a fresh installation of Raspbian-lite. My config is

[DatabaseUser]

login = root;
password = secret;
host = 127.0.0.1;
dbname = db_friend;
port = 3306;

[FriendCore]

fchost = 127.0.0.1;
fcport = 8080;
fcupload = storage/

[Core]

port = 8080;
SSLEnable = 0;

I have bunch of tables in mysql, so something is working :) . It seems that I'm only missing a file.

**Comment by IngoHohmann** [comment]
Same here, this is from the log: 

(core/worker_manager.c:65) Worker manager started 32 threads
  (network/file.c:57) Cannot open file resources//index.php (file does not exist?)..
  (network/http.c:100) Added text/html
  (network/http.c:100) Added close
  (network/http.c:1432) HTTP FREE END
  (system/cache/cache_manager.c:108)  cache size 0 file size 1918 cache max 1000000000
  (network/http.c:100) Added image/x-icon
  (network/http.c:100) Added close
  (network/protocol_http.c:362) --------------------------------------------------------------0
  (network/file.c:57) Cannot open file resources//index.php (file does not exist?)..
  (network/http.c:100) Added text/html
  (network/http.c:100) Added close
  (network/http.c:1432) HTTP FREE END
  (system/cache/cache_manager.c:176) File found in cache : resources//favicon.ico
  (network/http.c:100) Added image/x-icon
  (network/http.c:100) Added close
  (network/protocol_http.c:362) --------------------------------------------------------------0
  (network/file.c:57) Cannot open file resources//index.php (file does not exist?)..
  (network/http.c:100) Added text/html
  (network/http.c:100) Added close
  (network/http.c:1432) HTTP FREE END
  (system/cache/cache_manager.c:176) File found in cache : resources//favicon.ico
  (network/http.c:100) Added image/x-icon
  (network/http.c:100) Added close
  (network/protocol_http.c:362) --------------------------------------------------------------0
^C  (core/friend_core.c:799) [FriendCoreEpoll] Core shutdown in porgress
  (core/friend_core.c:1030) Closing Epoll file descriptor
  (core/friend_core.c:1039) [FriendCore] Goodbye.

**Comment by thomaswollburg** [comment]
Sorry about us not having the documentation in place.

The path to the startup file for the desktop is http[s]://[YOUR HOST OR IP]/webclient/index.html

**Comment by titlestad** [comment]
Correctly commented by Thomas :+1:
