### ISSUE TITLE
Status of browser support.

### ISSUE THREAD

**Issue by amiga23** [FriendSoftwareLabs/friendup#10]
On the login page it is written:
"Please use Google Chrome or Samsung Internet. Experimental support for Firefox and MS Edge."

But what does experimental support mean?

Does it really only work with official Google Chrome? Which Version?

Does it also work in Chromium?

In Firefox 56.0a1 (2017-06-30), Firefox 53.0.3 (64-Bit) and Firefox 54.0.1 (64-Bit) I do only get a black page after login.

In Chromium Version 61.0.3148.0 (Entwickler-Build) (64-Bit) and Safari Version 11.0 (13604.1.25.3.3) I do get some text, looks like a stylesheet is not applied correctly.
After resize (CMD -), I do get a background picture and square on the right center and one on the left bottom.

**Comment by titlestad** [comment]
Experimental support means that not everything is tested, or that there's some functions that may fail. To be honest, we haven't cataloged everything yet.

Firefox should work 100% - there's only some issues with Friend Chat and live conferences (in some peculiar cases).

Chromium should work 100% as well - it works exactly like Google Chrome.

What you might experience is a theme error. We have experienced this on some fresh installs - as our themes are compiled - and some times, if the theme isn't properly compiled, you may experience what you have described. We are looking into that. Try logging in while holding down the shift key and see if that helps. This will force the default theme.

Which version are you using? The one on https://friendsky.cloud - or have you compiled?

**Comment by amiga23** [comment]
I did just compile from github in a docker container FROM ubuntu:16.04

**Comment by amiga23** [comment]
Holding down shift while login does not change anything for me.
May I need more ports than 6502 and 6500?

**Comment by amiga23** [comment]
Web console in Firefox shows before login:
```
unreachable code after return statement[Learn More] workspace.js:36573:2
unreachable code after return statement[Learn More] workspace.js:45973:2
The character encoding of a framed document was not declared. The document may appear different if viewed without the document framing it. loginprompt
```
and after login:
```
--- Workspace.keys --- Object { client: Object, server: Object } workspace.js:45399:4
logged in... remove loading... workspace.js:45480:6
```

**Comment by amiga23** [comment]
In chromium I do get the following warning after login:

```
workspace.js:45946 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "https://192.168.99.100:6502/system.library/module/?module=system&command=theme&args=%7B%22theme%22%3A%22friendup%22%7D&sessionid=79093921920e6a35fbe2fc3b5f895d32a8f5a2ca".
(anonymous) @ workspace.js:45946
setTimeout (async)
refreshTheme @ workspace.js:45885
m.onExecuted @ workspace.js:45596
j.onload @ workspace.js:22420
proxy.onreadystatechange @ workspace.js:17159
XMLHttpRequest.send (async)
cAjax.send @ workspace.js:17366
Module.execute @ workspace.js:22423
(anonymous) @ workspace.js:45606
setTimeout (async)
m.onExecuted @ workspace.js:45578
j.onload @ workspace.js:22620
proxy.onreadystatechange @ workspace.js:17159
XMLHttpRequest.send (async)
cAjax.send @ workspace.js:17366
FriendLibrary.execute @ workspace.js:22641
login @ workspace.js:45622
doLogin @ VM162 loginprompt:106
checkKeys @ VM162 loginprompt:161
onkeydown @ VM166 loginprompt:27
```

**Comment by amiga23** [comment]
Maybe also important to document:
I did install php additionally, as it is not handled by install.sh. In Ubuntu 16.04 php7 get's installed, could that version cause the issue?

**Comment by amiga23** [comment]
Okay, I got it, had to install php-mysql.

Now it works in all above mentioned browsers.
