### ISSUE TITLE
'Say' command in Shell often does not work

### ISSUE THREAD

**Issue by idontbyte** [FriendSoftwareLabs/friendup#17]
I have only managed to get the say command to work once (the first time I tried it) all subsequent attempts have failed.

**Comment by thomaswollburg** [comment]
We tried to reproduce this here. The Say command uses functionality in Chrome. We tested in Firefox 54 as well and it worked here as well. Could you give us details about your browser, OS and broadband connection?

**Comment by titlestad** [comment]
The Say command uses the speech api. This is an open standard in browsers. It uses a server over the internet to generate the speech sound. So it needs a connection to this server to produce the desired results.

**Comment by idontbyte** [comment]
I am using Google Chrome and OSX, tried at work on Zen Internet business fibre and at home on Sky home fibre.
The first Say command works fine but the 2nd command hangs with the little spinner and never completes.
<img width="365" alt="screen shot 2017-07-07 at 09 55 53" src="https://user-images.githubusercontent.com/8790123/27950838-ab0776c2-62fa-11e7-96d0-e2cff6ec4327.png">

I've just noticed an error in the console on the 2nd attempt:

Uncaught TypeError: Failed to set the 'voice' property on 'SpeechSynthesisUtterance': The provided value is not of type 'SpeechSynthesisVoice'.
    at Say (workspace.js:16855)
    at SayWithText (workspace.js:39970)
    at Shell.execute (workspace.js:41749)
    at Shell.executeEvaluateInput (workspace.js:41489)
    at workspace.js:40698

**Comment by thomaswollburg** [comment]
Confirmed and fixed. This happens to users that have not yet stored language preferences. We see room for improvement but this fix should at least make sure the Say command always works.
