### ISSUE TITLE
Default credentials are not accepted

### ISSUE THREAD

**Issue by rabejens** [FriendSoftwareLabs/friendup#21]
I just installed friendup for the first time, and it won't let me log in. It says the credentials are invalid. Have they changed in the meantime?

Followup 1:
I investigated this and looked at the database. The install script only created FGlobalVariables table, no more.

Followup 2:
I manually inserted FriendCoreDatabase.sql into the newly created database but still no luck.

Followup 3:
I now started a separate MySQL server from a sameersbn/mysql Docker container, linked this to my friendup container and this does not work either.

**Comment by titlestad** [comment]
If you are using Linux Mint 18 - you might not have the php packages needed for accessing module calls. 

These are: **php-cli php-mysql php-gd php-curl php-imap**

Updating the installer now.

**Comment by rabejens** [comment]
I was using an Ubuntu 16 Docker container to install it in there, and even when I tore everything down and set it up anew, I couldn't log in.

**Comment by titlestad** [comment]
It should work just fine. 

First, see if your database has been installed. It should have many tables.
Second, make sure you're running Friend Core from your build directory.
Third, if all else fails, try to drop your "friendup" database, and re-run the install script.

I updated the Readme.md file today. Search for "serving kernel" and read how to start Friend Core from there.

**Comment by rabejens** [comment]
I just tried it again. After running the install script, it won't let me log in, and the database only has the FGlobalVariables table.

I dropped all tables in the database I use (it comes from the sameersbn/mysql container) and ran the install script for a second time.

When the installer asked me how to configure phpMyAdmin, or better, what webserver to use, I chose apache2 because this is what the install script pulls.

However, still no luck - it won't let me log in. Maybe the Docker container for Ubuntu 16 is a bit different from a "real" Ubuntu 16 and there is something going on that prevents the correct database initialization.

Are any additional services needed to be running besides from MySQL?

I'll try a virtual machine with a "real" Ubuntu server in it as a next step.

**Comment by titlestad** [comment]
Aha, are you using a Mac? We have had this problem on Macs - still trying to figure it out. It seems to be occurring randomly.

**Comment by rabejens** [comment]
Yes, I am using Docker for Mac and wanted to install this into a container. That's also the reason for my other comment in the suggestions thread to create an unattended installer. Ultimately, I want to get a Synology DiskStation in the not-so-far future and want to run it there, along with the other very similar project "Amibian.js".

**Comment by titlestad** [comment]
Ah cool :)

**Comment by rabejens** [comment]
Slightly off-topic: I know that a lot of former Amiga guys work on this, and I really believe that this direction is the true "next-gen" Amiga. PPC is just old stuff in a slightly newer form and the prices of Amiga stuff are prohibitive especially when it's not your main hobby. The community cooks in its own broth too much, as we Germans tend to say. We need a revolution like the cheap foam planes in the model aviation community and the accompanying cheap mail-order shops for the components. Something that is still interesting enough to tinker with but also reasonably priced to just "give it a go" and not lose too much when one dumps it. A new "A500", so to say. Everyone has a smartphone today, and the Raspberry Pi makes a great little fun tinkering tool and they are the true spiritual successors to the home micros of the 1980s and 1990s. Since the cloud is everywhere today, it makes perfectly sense that the new Amiga generation is cloud-based.

**Comment by titlestad** [comment]
Closing this issue, as it seems it has been resolved.
