### ISSUE TITLE
Maximizing and restoring a window will gradually change its size

### ISSUE THREAD

**Issue by AxelDominatoR** [FriendSoftwareLabs/friendup#29]
Every time a window is maximized and then restored to its normal dimensions, both the location and the size of the window will change slightly.

An easy way to reproduce is by opening any window (I did that with Home:) and aligning it with a reference point somewhere in the screen (I have my dock bar at the bottom, for example).
The first time you maximize and restore it, the position of the window will change slightly (initially the window is aligned to the top of the dock bar, after the first round of clicks it will be 1/3rd inside the dock bar).
Every other time you keep on repeating the same operation the window will not change position but will change width and height. It will keep growing until it occupies the full dimensions of the desktop.

(Edit: tested it and both height and width are affected)

**Comment by titlestad** [comment]
Fixed in the latest updates. The toolbar height wasn't counted in the calculation.
