### ISSUE TITLE
FriendCore does not start anymore ?

### ISSUE THREAD

**Issue by weiju** [FriendSoftwareLabs/friendup#34]
Hi,
not sure how to describe the problem, but FriendCore does not start for me anymore after a clean checkout and build.

I included some of the startup log that I see when I run the FriendCore tool on the command line
directly

weiju@monokuma ~/Development/friendup/build $ ./FriendCore 
 (main.c:123) 140165223790464 FRIEND_HOME set to: /home/weiju/Development/friendup/build
  (core/library.c:65) 140165223790464 Cannot open library with SysBase.library pointer! for properties.library
 140165223790464: (main.c 130) Core started log
 140165223790464: SystemBase Init
...
140165223790464: -----FC build: v1.0.0
140165223790464: -----FC id:  6045ffffffcbmonokuma-f185-25e1-30c4-cfb2-4cc30000000000000000000000000000000000000000000000000000000000000000000000000000000000
140165223790464: -----FC launched with options
140165223790464: -----Cache files: 1
140165223790464: -----HTTP SSL enabled: 1
140165223790464: -----WS SSL enabled: 1
140165223790464: -----Communication SSL enabled: 0
140165223790464: -----FCPort: 6502
140165223790464: -----WSPort: 6500
140165223790464: -----CommPort: 6503
140165223790464: -----CommRemotePort: 6504
140165223790464: -----SSH_SERVER_PORT 6505
140165223790464: -----SQL connections: 32
140165223790464: -----UserFileShareCache (per drive): 102400000
140165223790464: ------------------------------------------------------
 (network/http_client.c:167) 140165223790464 ERROR reading response from socket  (network/websocket.c:1807) 14
...
140165223790464: [SystemBase] Create DOSDrivers
140165223790464: [SystemBase] ----------------------------------------
 (system/fsys/device_handling.c:147) 140165223790464 [RescanDOSDrivers] Scanning for DOSDrivers
iniparser: cannot open /home/weiju/Development/friendup/build/devices/DOSDrivers/INRam/dosdriver.ini
  (system/fsys/dosdriver.c:122) 140165223790464 [ERROR]: Handler not found cannot create DOSDriver!

...

140165223790464: [SystemBase] ----------------------------------------
' invalide/file/magic.mgc, 1: Warning: offset `�
/usr/share/file/magic.mgc, 6: Warning: offset `Firmware v' invalid
/usr/share/file/magic.mgc, 7: Warning: offset `' invalid
/usr/share/file/magic.mgc, 8: Warning: offset `' invalid
/usr/share/file/magic.mgc, 13: Warning: offset `' invalid
/usr/share/file/magic.mgc, 15: Warning: offset `::[	frontEndVersion = ' invalid
' invalide/file/magic.mgc, 20: Warning: offset `
/usr/share/file/magic.mgc, 22: Warning: offset `East_Side_Invertationa' invalid
/usr/share/file/magic.mgc, 25: Warning: offset `The_Incinerator_Plant' invalid

**Comment by stefkosdev** [comment]
Hey

I'm checking that. Will post here information when I will find where problem is or when I will have questions.

**Comment by stefkosdev** [comment]
1 is your machine connected to internet?
2 can you change one file and give me results after compilation?
core/core/friendcore_info.c
and disable this part of code:
BufString *bs = HttpClientCall( c, geoProvider );
			if( bs != NULL )
			{
				fci->fci_LocalisationJSON = StringDuplicate( strstr( bs->bs_Buffer, "\r\n\r\n" ) );
				DEBUG("[FriendCoreInfoNew] Localisation string received %s\n", fci->fci_LocalisationJSON );
				BufStringDelete( bs );
			}

**Comment by weiju** [comment]
Hi, thanks for getting back to me this quickly. Yes, initially I am connected to the Internet. I also commented out the above lines and recompiled with make (is this sufficient ?). The result is pretty much the same as before though.

**Comment by stefkosdev** [comment]
Hey

Last time I added functionality which takes infrormation about geolocation from another server on the web and I was sure it was making problem for you.
Will ask you about another things:
1 post your cfg.ini file
2 paste me somewhere (pastebin) full log from launching FC.

**Comment by weiju** [comment]
I put the log on 
https://pastebin.com/KAUPaaPL

The configuration file is below, thanks !

My cfg.ini:

```
[DatabaseUser]
login = friendup
password = friendup1
host = localhost
dbname = friendup
port = 3306

[FriendCore]
fchost = localhost
port = 6502
fcupload = storage/

[Core]
port = 6502
SSLEnable = 1

[FriendNetwork]
enabled = 0

[FriendChat]
enabled = 0
```

**Comment by stefkosdev** [comment]
For me this looks fine (log).
Did you tryed to login by using browser on same machine + url   https://localhost:6502/webclient/index.html ?

**Comment by weiju** [comment]
you are right, that worked for me, the real problem was that I've forgot to specify the prococol. Sorry for the false alarm.

**Comment by stefkosdev** [comment]
np. really.
I will check your log again, maybe some messages should be displayed in non-debug version too.
