### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by hjozwiak** [FriendSoftwareLabs/friendup#42]
Hello,

Not sure if this is the right place for this, but I can't seem to be able to build the Friendup system. Here is the compilation.log from the attempt.
[compilation.log](https://github.com/FriendSoftwareLabs/friendup/files/1464824/compilation.log)
Any thoughts or ideas?

**Comment by stefkosdev** [comment]
Hey

Can you tell me which linux distro are you using and gcc version?
Somehow it cannot find some function which are available in code.

P.S.Soon we will release our latest code

**Comment by hjozwiak** [comment]
The GCC version is 7.2.1 20171224, with Arch Linux being the operating system.

**Comment by stefkosdev** [comment]
I will download image now and check.
Will do my tests on archlinux-2018.01.01-x86_64.iso

**Comment by stefkosdev** [comment]
I found out that arch linux have some problems with openssl, take a look:
https://github.com/openwrt/openwrt/issues/372

**Comment by stefkosdev** [comment]
I'm sure I fixed that problem (fix for Kali and Arch linux)
