### ISSUE TITLE
Missing i18n strings in calendar

### ISSUE THREAD

**Issue by dm8tbr** [FriendSoftwareLabs/friendup#44]
Noticed at least `i18n_event_name`, `i18n_leadin` and `i18n_save`:

![screenshot_20180114_082604](https://user-images.githubusercontent.com/2073288/34915496-9cdc737a-f91f-11e7-8078-425ca26d44b9.png)

**Comment by titlestad** [comment]
Yes, in fact, the Calendar editor is an open sore in Friend at the moment. It ought to be integrated with Exchange, iCal etc - but this work hasn't been given much focus right now. In enterprise installations, this feature ought to be turned off.

The basic framework to make integrations is there, but like I said, it's not really far in development yet.

**Comment by titlestad** [comment]
Fixed. :-)
