### ISSUE TITLE
install script fails on fresh Debian 9 installation due to undeclared dependency on build-essential (or parts of)

### ISSUE THREAD

**Issue by dm8tbr** [FriendSoftwareLabs/friendup#6]
On a fresh minimal installation of Debian 9 the install.sh script will fail.
> friendup/install.sh: line 241: make: command not found

**Workaround:**
`apt install build-essential`
(Explicitly installing just `make` would probably work too, but then the script would likely fail further down.)

**Comment by dm8tbr** [comment]
I expect this to fail on a fresh Ubuntu server too but will spin one up to confirm that and other issues in parallel.

**Comment by titlestad** [comment]
Please take a look here and see if this helps you:

https://github.com/FriendSoftwareLabs/friendup/blob/master/docs/Compiling.txt

**Comment by dm8tbr** [comment]
I just tried this on ubuntu 16.04.2 and there it runs an extensive installation of dependencies. So indeed as you said in #5 its just that the Debian side is not implemented in the script.
Let's close this one and just use #5 to work out how to add Debian support.
