### ISSUE TITLE
404 on /publickey/ when running in non-SSL mode

### ISSUE THREAD

**Issue by amiga23** [FriendSoftwareLabs/friendup#9]
When loading the login page /webclient/index.html I see error 404 (Not found) in the developer tools -> networks on trying to access /publickey/

**Comment by titlestad** [comment]
Yes, this is actually known. It will not happen if you run Friend in SSL mode. It doesn't have a public key because it's not encrypted. Still, need to fix it for people who want to run in non-SSL mode locally. :) Good call.

**Comment by amiga23** [comment]
Okay, when running in SSL mode it works fine.

I've used the following command to create a selfsigned certificate in build/cfg/crt
mkdir build/cfg/crt
sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout build/cfg/crt/key.pem -out build/cfg/crt/certificate.pem
